### ISSUE TITLE
Track.GetInfoAsync does not return "userplaycount"

### ISSUE THREAD

**Issue by roflmuffin** [inflatablefriends/lastfm#111]
It looks like if you pass a username to the GetInfoAsync method, the number of plays returned is the total plays, regardless of the username provided.

When you hit this API outside of the client, there are two properties, "playcount" (the one returning from the API), and one called "userplaycount". 

Should we add this value to the track info, or modify it to be the user play count when providing a username?

**Comment by rikkit** [comment]
Hi @roflmuffin, thanks for creating the issue. I would be in favour of providing both bits of information if possible, i.e. two properties on the track object where UserPlayCount is null if not available on the API response.

I really need to get #107 sorted before any released can be made for this package, but if you would like to send a PR to fix this issue I'll be sure to get that reviewed and merged in!

**Comment by rikkit** [comment]
@roflmuffin This is now released in the 1.1.0 package. Thanks
