### ISSUE TITLE
User.getRecentScrobbles is missing the "To" and "Extended" parameter

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#113]
According to [the api](https://www.last.fm/api/show/user.getRecentTracks) these parameters are optional for the command, but I think they would be really helpful.

**Comment by coczero** [comment]
And I just noticed I get an MissingParameters error status when using User.GetRecentScrobbles

**Comment by coczero** [comment]
Hmm, weird. I will try again once I'm home. Though I just call UserApi.GetRecentScrobbles(Username). (i also tried with the optional parameters)

**Comment by coczero** [comment]
Ok, so the "MissingParameters" error comes from the default page parameter being "0", last.fm wants that parameter between 1 and 1000000 though.

**Comment by rikkit** [comment]
Thanks for looking into this - I suppose the default should be changed to 1.

**Comment by L-Dogg** [comment]
@rikkit Can I work on this one?

**Comment by rikkit** [comment]
Closed by #144
