### ISSUE TITLE
Example as is from readme never genereates error

### ISSUE THREAD

**Issue by ColorTwist** [inflatablefriends/lastfm#117]
I tried the following code: 
```
   var client = new LastfmClient("apikey", "secret api");
            var response = client.Album.GetInfoAsync("Grimes", "Visions");
            LastAlbum visions = response.**Content**;
```
Receving an error on Content:

> 	'Task<LastResponse<LastAlbum>>' does not contain a definition for 'Content' and no extension method 'Content' accepting a first argument of type 'Task<LastResponse<LastAlbum>>' could be found (are you missing a using directive or an assembly reference?)

I am using WinForms and downloaded the SDK with NuGET

**Comment by rikkit** [comment]
Hi @ColorTwist, can you tell me what versions of Visual Studio, .Net, and the NuGet package you're using? And if possible, would you be able to share the project where you get this error?

**Comment by coczero** [comment]
@ColorTwist you need to await the GetInfoAsync call.
Like this `var response = await client.Album.GetInfoAsync("Grimes", "Visions");`
Otherwise you just get a task back (which obviously does not have a `Content `property

**Comment by rikkit** [comment]
Ah oops! Didn't read the code properly or realise it's a compile warning. Ta @coczero

**Comment by rikkit** [comment]
Will update the code sample in the readme :)
