### ISSUE TITLE
How to become contributor ?

### ISSUE THREAD

**Issue by ColorTwist** [inflatablefriends/lastfm#121]
I added a new function called: GetTopAlbumsByMbidAsync and i want to push it for the benefit of all.

When i try to push it i get that i do not have permission:

> 
> remote: Permission to inflatablefriends/lastfm.git denied to ColorTwist.
> fatal: unable to access 'https://github.com/inflatablefriends/lastfm.git/': The requested URL returned error: 403
>

**Comment by rikkit** [comment]
Hi @ColorTwist! You will need to **fork** this repository to your own account, then send a **pull request**. I will then review your changes and merge them into the code assuming all is good.

You can read more about this process here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks!

**Comment by ColorTwist** [comment]
i see, need to learn how to fork, i already use Source Tree to get the master repository of this git, does it mean i "forked" it ? :)

**Comment by rikkit** [comment]
You've got a copy of the repo on your computer - you need to have one on your GitHub account also. Click the fork button at the top right of this page, then make any changes you want to make in that repository. Then send a pull request.

A clone is a copy of a repository
A fork is a clone that's publicly accessible :)
