### ISSUE TITLE
TypeLoadException problem with SQLite scrobbler

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#122]
Since the new update the SQLite scrobbler is not working anymore.
I get the following error message:
`TypeLoadException: The method "RemoveFromCacheAsync" of type "IF.Lastfm.SQLite.SQLiteScrobbler" of assembly "IF.Lastfm.SQLite, Version=0.2.0.211, Culture=neutral, PublicKeyToken=null" has no implementation.` (translated from German)

I'm using the nuget package of the SQLite scrobbler but I already tried to build it myself.

**Comment by rikkit** [comment]
I haven't updated the SQLite package yet - see #115. You should be able to build and package it from source though.

1. Update `sqlite-net-pcl` to latest version
1. Build solution in release mode
1. Change the platform target in `.nuget/Inflatable.Lastfm.SQLite.nuspec` to `lib\netstandard1.1`
1. Change the version in `.nuget/Package-Versions.ps1` to `1.0.0` (local source builds get this version, this would be `1.1.1` for the CI server)
1. Run `.nuget/pack.ps1`
1. The nupkg file generated should work.

I'm quite busy this week but when I get a chance I'll push up the SQLite package (I wanted to test it in a real application).
