### ISSUE TITLE
Add user specific info for AlbumApi.GetInfo

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#127]
According to https://www.last.fm/api/show/album.getInfo you can get user specific info like playcount of an album.

**Comment by c-d** [comment]
Hi, I've submitted PR #130 for this.

Note that the last.fm API is a bit confusing - userplaycount is a sum of all of the scrobbles by that user _for all tracks on the album_, not the number of times a user has played the album in its entirety.
