### ISSUE TITLE
Add method Artist.GetTopAlbumsByMbidAsync

### ISSUE THREAD

**Issue by mew22** [inflatablefriends/lastfm#129]
Is it possible to add this method, based on the existing Artist.GetTopAlbumsAsync but with Mbid ?

**Comment by rikkit** [comment]
Hi @mew22, if the API will accept this parameter, it's definitely possible to add. Unfortunately I've got very little free time at the moment to implement it for you, but if there is a pull request, I'll make time to merge it in and release. Thanks

**Comment by rikkit** [comment]
@klinge go for it :)

**Comment by klinge** [comment]
I'll start with trying to get tests to run on .Net Core/Linux. If I fix that then I will continue with this one.

**Comment by GmausDev** [comment]
Its still open?

**Comment by rikkit** [comment]
@GmausDev yep!

**Comment by GmausDev** [comment]
@rikkit  i looking at #141 PR and its look like done.?

**Comment by rikkit** [comment]
Ah, sorry. Yes it looks like it is complete.
