### ISSUE TITLE
Test projects - dependency on .Net Framework 4.6.2

### ISSUE THREAD

**Issue by klinge** [inflatablefriends/lastfm#135]
I'm on linux and Visual Studio Code. I cloned the repo and can build the main project without any trouble. But when trying to build the test projects I get the error below: 

`error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. `

Since it is not possible to install/run the full .NetFramework on linux there seems to be no way to get tests running. Would it be possible to target .Net Standard/.Net Core instead in the test projects?

**Comment by rikkit** [comment]
I'm sure it's possible - I'm all for making the project more cross platform. However I don't have time to work on this. You could make .Net Core test projects with the same files and I think it'd work. Happy to accept a PR for this.
