### ISSUE TITLE
Get popular artists by genre (pop, rock, etc..) and country

### ISSUE THREAD

**Issue by ColorTwist** [inflatablefriends/lastfm#139]
I know there  `getTopArtistsin`  in geo section, but it always returns the same popular bands in different order but not local bands of a country and without genre result.
(https://www.last.fm/api/show/geo.getTopArtists)
Would it be possible to get popular artists by genre and country?
For example: a list of X popular artists in ROCK genre from United States.

**Comment by rikkit** [comment]
This isn't is a feature that the Last.fm API supports (this is an independently run project) - I don't think Last.fm even records the origin country of each artist.

So you'd have to look elsewhere, then cross-reference it with the popularity lists from Last.fm. Origin info is available on MusicBrainz for some of the more popular artists, but as with a lot of music info databases, there are a lot of gaps. You'd have to try it out and see how much information you can gather.
