### ISSUE TITLE
Add LastResponseStatus for Login Required

### ISSUE THREAD

**Issue by th0mk** [inflatablefriends/lastfm#150]
When a users profile is private, a request like `User.getRecentTracks` can return error 17:
```json
{
    "error": 17,
    "message": "Login: User required to be logged in"
}
```
This error code does not exist in the `LastResponseStatus` enum.

**Comment by rikkit** [comment]
Hi @th0mk, thanks for this report. I don't currently have time to do much work on this library, so if you can send a PR that'd be great! IIRC the value just needs adding here: https://github.com/inflatablefriends/lastfm/blob/master/src/IF.Lastfm.Core/Api/Enums/LastResponseStatus.cs

**Comment by th0mk** [comment]
Thanks, I will do a PR today.
Note: this response isn't mentioned anywhere in the [Last.FM docs](https://www.last.fm/api/show/user.getRecentTracks), but they're pretty outdated anyways..

**Comment by th0mk** [comment]
Hi there, do you maybe have some time to look at my PR?
