### ISSUE TITLE
Porting the lib to .Net Standard?

### ISSUE THREAD

**Issue by tolbxela** [inflatablefriends/lastfm#157]
I like this library very much. The developers did a very good job!
But it is a bit outdated. 
What about porting the library to .Net Standard?

**Comment by rikkit** [comment]
Thanks!

It's already targeting `netstandard1.1`. https://github.com/inflatablefriends/lastfm#platform-compatibility

I'm a bit out of the loop on .Net packaging. is there a platform that you're not able to use this library on? Or is there a newer version of .Net Standard it should be on?

**Comment by tolbxela** [comment]
> It's already targeting `netstandard1.1`. https://github.com/inflatablefriends/lastfm#platform-compatibility
> 
> I'm a bit out of the loop on .Net packaging. is there a platform that you're not able to use this library on? Or is there a newer version of .Net Standard it should be on?

No, I can use the lib without problem. 
But .Net Standard 1.1 is 7 versions behind of the current .Net Standard 2.1.

I just thought, it does make sense to upgrade it.

**Comment by rikkit** [comment]
As far as I understand it, you don't need to upgrade versions of  .Net Standard unless you need something in the new version. Updating it means you potentially reduce the number of platforms your library can be used on.

Happy to be corrected, but I think it's fine as it is.

**Comment by tolbxela** [comment]
> As far as I understand it, you don't need to upgrade versions of .Net Standard unless you need something in the new version. Updating it means you potentially reduce the number of platforms your library can be used on.

Yes, you are right. 
 
> Happy to be corrected, but I think it's fine as it is.
Ok. :-)
