### ISSUE TITLE
Artist API

### ISSUE THREAD

**Issue by rikkit** [inflatablefriends/lastfm#32]
Issue to track remaining artist commands

[API Progress](https://github.com/inflatablefriends/lastfm/blob/master/PROGRESS.md)
- [x] artist.getTopArtists
- [ ] artist.addTags
- [ ] artist.getCorrection
- [ ] artist.getPastEvents
- [ ] artist.getPodcast
- [ ] artist.getTopFans
- [ ] artist.removeTag

**Comment by zumicts** [comment]
The GetSimilarArtist method doesn't have a page parameter, does the api allow paging here? (I know you can limit it)

**Comment by rikkit** [comment]
AFAIK none of the getSimilar methods have paging. I should put that in their XML Docs.

**Comment by rikkit** [comment]
Tidying issues
