### ISSUE TITLE
Enable client to provide their own HttpClient

### ISSUE THREAD

**Issue by rikkit** [inflatablefriends/lastfm#41]
[HttpClient should be persisted for as long as the application needs it](http://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed). Currently each call to the SDK creates a new one.

Work is to allow an HttpClient to be registered with the SDK. Simplest way seems to be IoC/DI but need to keep it simple to use for applications without that in place.

**Comment by zumicts** [comment]
What would be more optimal performance wise, new client on every request or have one persist during the app lifetime?

**Comment by rikkit** [comment]
Persist, will use up a bit of memory though. This issue will let you do either though.
