### ISSUE TITLE
Can't login with LastAuth

### ISSUE THREAD

**Issue by zumicts** [inflatablefriends/lastfm#45]
Testing the demo, it doesn't throw an exception is just keeps waiting.

Debugging I found out that the problem is in the signature generation, in ToMD5()

Anybody else experiencing this?

EDIT: there is a System.IO.FileNotFoundException happening, not sure if is trying to load an assembly and failing.

EDIT: decided to use a custom implementation of MD5 instead of the MyConvert package and everything is working. See [here](https://github.com/zumicts/lastfm/commit/1299f51c8133e0b1fa6b4cf900e515d00500cb2b)

**Comment by rikkit** [comment]
Fixed by merging #46
