### ISSUE TITLE
Tag API

### ISSUE THREAD

**Issue by rikkit** [inflatablefriends/lastfm#49]
Issue to track remaining tag methods
- [x] tag.getInfo
- [x] tag.getSimilar
- [x] tag.getTopAlbums
- [ ] tag.getTopArtists
- [x] tag.getTopTags
- [ ] tag.getTopTracks
- [ ] tag.getWeeklyArtistChart
- [ ] tag.getWeeklyChartList
- [ ] tag.search
- [ ] track.addTags
- [ ] track.getTags
- [ ] track.getTopTags
- [ ] track.removeTag
- [ ] user.getPersonalTags
- [ ] user.getTopTags
- [ ] album.addTags
- [ ] album.removeTag
- [ ] artist.addTags
- [ ] artist.removeTag
- [ ] chart.getTopTags

**Comment by rms81** [comment]
When writing tag.getInfo, got the feeling that the Count property of Tag should be named, or at least the corresponding json attribute (don´t want to break anything :) ) , should be taggings, witch indicates the total number of times the tag has been used.

**Comment by rikkit** [comment]
Taggings is called Count in other APIs, plus it's a simpler name. So imo GetInfo should set the count property to the value of taggings.

```
var countToken = token.SelectToken("count") ?? token.SelectToken("taggings");
```

**Comment by rms81** [comment]
Totally agree. Will do that.

**Comment by rikkit** [comment]
Tidying issues
