### ISSUE TITLE
MyConvert causing windows phone store certification failure

### ISSUE THREAD

**Issue by factormystic** [inflatablefriends/lastfm#56]
Any way to avoid this dependency?

    Error Found: The supported APIs test detected the following errors:
    This API is not supported for this application type - Api=System.Security.Cryptography.MD5CryptoServiceProvider. Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Security.Cryptography.HashAlgorithm. Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Security.Cryptography.MD5. Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.SerializableAttribute. Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Char.ToString(System.IFormatProvider). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Security.Cryptography.MD5CryptoServiceProvider.#ctor. Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Security.Cryptography.HashAlgorithm.ComputeHash(System.Byte[]). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Globalization.TextInfo.ToTitleCase(System.String). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Text.Encoding.get_ASCII. Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Text.Encoding.GetString(System.Byte[]). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.String.Format(System.String,System.Object,System.Object,System.Object). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Globalization.CultureInfo.GetCultureInfo(System.String). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Reflection.PropertyInfo.op_Inequality(System.Reflection.PropertyInfo,System.Reflection.PropertyInfo). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.SerializableAttribute.#ctor. Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.
    This API is not supported for this application type - Api=System.Reflection.PropertyInfo.op_Equality(System.Reflection.PropertyInfo,System.Reflection.PropertyInfo). Module=MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089. File=MyConvert.dll.

**Comment by zumicts** [comment]
Actually, isn't the latest source code not using MyConvert?

**Comment by factormystic** [comment]
I was using the nuget version. I removed that and built from source and am resubmitting to the store now... assuming it will work, because MyConvert is no longer referenced.

**Comment by rikkit** [comment]
Yep - you don't need it anymore, you just need to remove the reference NuGet adds.

I forgot to unlist the dependency from the NuGet package (#55)... sorry about that. This'll be fixed in the next release.

**Comment by rikkit** [comment]
By the way @factormystic which app are you building? On my list for the next release is doing some blog posts/ tutorials so there's an opportunity for a bit of free promotion... :smile: (applies for you too @zumicts + anyone else building apps with the SDK)

**Comment by zumicts** [comment]
@rikkit free promotion? count [me](www.windowsphone.com/s?appid=c02aae72-99d3-480f-b6d2-3fac2fed08a7) in! :laughing:

**Comment by factormystic** [comment]
Sure, I'll take a shoutout: https://www.windowsphone.com/s?appid=df15a2e9-9ec3-454a-86f2-1c83a488b6cd

**Comment by zumicts** [comment]
@factormystic nice app, gives even more usage to onedrive!
