### ISSUE TITLE
Update package on nuget

### ISSUE THREAD

**Issue by kasthack** [inflatablefriends/lastfm#65]

**Comment by rikkit** [comment]
Yeah, probably a good idea to push something up. Was going to finish #63 first but no harm in an interim release. I'll do this either today or tomorrow.

Checklist
- [ ] #57
- [ ] unit tests for library commands

**Comment by rikkit** [comment]
v0.1.5 is up on NuGet, [release note is here](https://github.com/inflatablefriends/lastfm/releases/tag/v0.1.5)
