### ISSUE TITLE
Should use ConfigureAwait(false) for internal async methods

### ISSUE THREAD

**Issue by rikkit** [inflatablefriends/lastfm#68]
More info: http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by zumicts** [comment]
there is a handy resharper plugin for this, not sure if you're using R#?

**Comment by rikkit** [comment]
I just installed [this one](http://resharper-plugins.jetbrains.com/packages/ConfigureAwaitChecker.v9), but it doesn't seem to raise any warnings where I would expect it to. Is there any configuration needed?

**Comment by zumicts** [comment]
That was the one I was talking about. Is it enabled?

**Comment by rikkit** [comment]
Tidying issues
