### ISSUE TITLE
The progress reporter is broken

### ISSUE THREAD

**Issue by yaurthek** [inflatablefriends/lastfm#71]
...and has been since this commit https://github.com/inflatablefriends/lastfm/commit/211fb3a559bec3598d942c84dccf7e3a4c4b7422#diff-3721d66d11b6801d053f3680f7e08f74 .

This is because `ScrobbleCommand`  now has two constructors taking two arguments, and it breaks the `Activator.CreateInstance()` with an `AmbiguousMatchException` when creating the Command instances to get their `Method` property.

It should have been possible to use the `ContructorInfo.Invoke()` directly to avoid this problem, but in this case it does not work since passing null as the arguments throws a `NullReferenceException` in the constructor.

Anyway, I think this is just a symptom of a deeper problem: I'm convinced it should not be necessary to create a Command instance to get its corresponding api method name...

**Comment by rikkit** [comment]
Fixed by #72
