### ISSUE TITLE
track.AlbumName and track.Duration are null?

### ISSUE THREAD

**Issue by jjgh** [inflatablefriends/lastfm#83]
Hi, I'm working on my first C# project so please forgive me if I am reporting something incorrectly.
I am finding that I am getting null objects when I try to access track.AlbumName and track.Duration, do you think it's due to something that has changed in LastFm API?
Thanks!

```
var topTracks = await myLastfmClient.Artist.GetTopTracksAsync(artist.Name);
foreach (var track in topTracks) {
    if (track.AlbumName == null) { Console.WriteLine("albumName is null"); }
    if (track.Duration == null) { Console.WriteLine("duration is null"); }
}
```

**Comment by rikkit** [comment]
Hey

Last.fm data can be quite patchy in some places, because a lot of it is crowdsourced. I know that not all tracks have duration data, but I would have expected them all to have album name data. 

The best way to check whether this is the SDK or the API is to check the JSON response from the API. Which artists are you testing?

**Comment by jjgh** [comment]
Cool, thanks for your answer. 
First off, I was testing with very popular artists (Queen, Pink Floyd, AC-DC, ...) and I could never find either the duration or the album name for a track, not even once. 

Secondly, yes, I thought of inspecting the JSON response from the API but I couldn't remember the syntax for the request and also 1) I couldn't find it by reading your library code, sorry but I am not able to inspect some c# library code yet (I actually tried but it's as if I couldn't find the code itself! I am thinking that it could be because I installed IF lastfm with Nuget, only getting the binaries and not the source? I could be ridiculously wrong here... ) 2) I went looking on the last.fm website, because the lazy me remembers they had a clickable example URL for any API request, but in order to see it you have to be logged on, and the login system was errorimg out badly at my end... (not setting me as logged in even after successfully logging in...). 
Yes I could actually go read the api doc in order to understand how to build a request (and I will do!) , but since I'm very motivated with learning c# at this time, what I did instead was using the Newtonsofts Json library to serialize to JSON (and pretty print) the *track* object as soon as it got assigned with last.fm response. Well yes I know it was a bit useless but still... What I could observe was that trackAlbum and Duration - but also (sorry, I forgot this important part of the story :) , I will integrate it shortly) - were always null...

So yeah if you find something else in the meantime please let me know!
Thanks.

**Comment by jjgh** [comment]
Is inflatablefriends/lastfm querying the last.fm API like the following request does? Because this will contain album information and track duration too..

http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=f5f149ffcdf2e0db0888f6c477c4abc1&artist=cher&track=believe

**Comment by rikkit** [comment]
Hi @jigh. I don't have time this weekend to help unfortunately! It sounds like you should look into a software called Fiddler. This lets you see the http requests made by an application. You can also check out the tool i wrote to make testing the last.fm api better. Details on how to use it are in contributing.md in this repo.

I'll try and check in over the next couple days to answer quick questions. I cant spend a lot of time until the coming Monday though!

-----Original Message-----
