### ISSUE TITLE
Scrobble track with info from LastTrack

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#89]
I can't seem to scrobble a track which pulls its info from a LastTrack.
I narrowed the problem down to the TimePlayed Property.
If I create my Scrobble with DateTime.Now, it works:
`scrobbles.Add(new Scrobble(vm.Scrobble.ArtistName, vm.Scrobble.AlbumName, vm.Scrobble.Name, DateTime.Now));` <--- This Scrobble will be successfully scrobbled.

vm.Scrobble is the LastTrack.

But if I try to use the LocalDateTime of the TimePlayed of the LastTrack, like this:
`scrobbles.Add(new Scrobble(vm.Scrobble.ArtistName, vm.Scrobble.AlbumName, vm.Scrobble.Name, vm.Scrobble.TimePlayed.Value.LocalDateTime));` <--- still says successfully scrobbled, but isn't actually scrobbled.

Any ideas?

**Comment by rikkit** [comment]
What's the value of each datetime compared to UTC? Could be a timezone thing? The Last.fm API [has some rules](https://github.com/inflatablefriends/lastfm/blob/master/doc/scrobbling.md#things-to-know) about scrobbles, could be it's rejecting a future datetime.

**Comment by coczero** [comment]
![TimePlayed obj](https://ibin.co/2i0xdSp2vtSl.png)

So basically, that means, that the LocalDateTime lies in the future, at least for the last.fm servers?
Sadly, UtcDateTime doesn't work either. Says successfully scrobbled, but the scrobble does not appear on my last.fm page :(
I also tried other Properties of the TimePlayed prop, but the only one that seemed to work was the DateTime property itself. But then in my scrobbles, that scrobble is 2 hours late...

**Comment by rikkit** [comment]
Have you tried using just ```vm.Scrobble.TimePlayed.Value```? I would have expected DateTimeOffset.UtcDateTime to work the same as the DTO, but it's worth a try.

Also can you check the ```Ignored``` property on the response you get back from the Scrobbler class? This should show if any scrobbles were ignored for datetime reasons.

**Comment by coczero** [comment]
Same result unfortunately. Says successfully scrobbled, but it's not showing on my page.
Ignored is empty.

![Ignored](https://ibin.co/2i2zmWfU4Rvt.png)

**Comment by rikkit** [comment]
Is it the same track/artist each time? The API rejects duplicate scrobbles but I would have expected those to appear in the Ignored property. 

Any chance you can capture the scrobble request using Fiddler (or similar) so I can try reproduce this?

**Comment by coczero** [comment]
Hmm you are right, if I add a second to the value it works... =D

**Comment by rikkit** [comment]
Nice! I guess I can close this issue then :+1:
