### ISSUE TITLE
All albums I fetch dont have tracks

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#91]
Is this yet to be implemented or is this a bug? Every album I fetch does not have tracks, even though I checked the last.fm page of that album and it has tracks.
I fetch like this: 
`var response = await MainViewModel.Client.Album.SearchAsync(SearchText);`
I get a lot of albums from my searches but none of them has tracks. Am I simply doing something wrong?

**Comment by rikkit** [comment]
Albums from the search api don't contain tracks in their responses, you will have to use ```Album.GetInfoAsync``` for each album you want a list of tracks for.
