### ISSUE TITLE
How would I go about "unauthentification" of a client?

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#93]
In my app the user can switch between accounts via a list of added accounts. If he removes the currently active user I want the client to no be authenticated anymore. But nothing I tried so far worked. I tried to load an empty user session, get the client token with empty data, dispose the Auth object... any ideas?

**Comment by rikkit** [comment]
You need to make a new LastfmClient object. You can load an existing UserSession object into it using ```client.Auth.LoadSession(cachedUserSession)```. If you don't load one in, the user is not authenticated.

The API is a little awkward here I realise, the ```LastAuth``` class should have a "log out" method - this would save having to create a new LastfmClient each time you switch account.
