### ISSUE TITLE
User.GetTopArtists fails with "Missing parameter"

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#99]
I call the following line: `var response = await MainViewModel.Client.User.GetTopArtists(Username, TimeSpan, 0, Amount);` where 'Username' is 'coczero', 'TimeSpan' is 'Overall' and 'Amount' is 20. The response fails with the Status "MissingParameters".
Any ideas?

**Comment by rikkit** [comment]
Is the 0 page number? Try setting it to 1. The API is inconsistent as to whether paging is 0 or 1 indexed. I can look at this a bit later.

**Comment by coczero** [comment]
Yea this fixes it... alright, I guess =D

**Comment by rikkit** [comment]
Sweet. I'm planning to put in like a pager object that knows the default value for each api call. For now just try 0 or 1 :)
